### ISSUE TITLE
High score saving

### ISSUE THREAD

**Issue by saharsh-agrawal** [saharsh-agrawal/Minesweeper#1]
Once the project is exported to be used, as a jar file, the high score file becomes uneditable by code. Some modification in the high score storage and game export is required to save the high score for each level.

**Comment by IshaanGaba** [comment]
My solution to the above problem:-

To resolve these issues, high scores will be stored in a writable JSON file located in the user's home directory. The JSON format provides a structured way to save high scores for each level.This file will be automatically  if it does not already exist. The game will use this file to read, update, and store high scores persistently.
By using JSON, the system can efficiently store and retrieve high scores for each difficulty level, providing a scalable and user-friendly mechanism for high score management.This solution ensures that high scores remain editable and persistent, even after the game is exported as a JAR file.

**Comment by saharsh-agrawal** [comment]
Sure. Please go ahead and try to implement this. I am assigning this issue to you.

Also, do connect on the discord server (given on the KWOC website) to have more detailed discussions and interactions.
